
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: springcloud-eureka-7001
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    service-url:    
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
---
spring:
  profiles: test
  application:
    name: springcloud-eureka-7002
server:
  port: 7002 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    service-url:   
      defaultZone: http://${eureka.instance.hostname}:7002/eureka/

